# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - packages/api-userprofile

variables:
  - group: BackendResources

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  displayName: 'Setting environment variables'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      export COSMOS_ENDPOINT=$(SECRET_COSMOS-ENDPOINT)
      export COSMOS_KEY=$(SECRET_COSMOS-KEY)

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'ci'
    workingDir: 'packages/api-userprofile'

# - task: Npm@1
#   displayName: 'Linting & Testing'
#   inputs:
#     command: 'custom'
#     workingDir: 'packages/api-userprofile'
#     customCommand: 'run test'

- task: Npm@1
  displayName: 'Package'
  inputs:
    command: 'custom'
    workingDir: 'packages/api-userprofile'
    customCommand: 'run package'

- task: CopyFiles@2
  displayName: 'Prepare build artifact'
  inputs:
    SourceFolder: 'packages/api-userprofile/.serverless'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'api-userprofile'
    publishLocation: 'Container'
