# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

variables:
  - group: BackendResources
  - group: AzureDeployCredentials

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'ci'
    workingDir: 'packages/api-userprofile'

- task: DownloadBuildArtifacts@0
  displayName: 'Download Build Artifact'
  inputs:
    buildType: 'specific'
    project: 'paddleboard'
    pipeline: 'Build.UserProfileAPI'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latestFromBranch'
    branchName: 'refs/heads/master'
    artifactName: 'api-userprofile'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: Bash@3
  displayName: 'Deploying Serverless Azure Functions'
  inputs:
    targetType: 'inline'
    workingDirectory: 'packages/api-userprofile'
    script: |
      set -e
      npx serverless deploy --package $(System.ArtifactsDirectory)/api-userprofile/pdlbrd-user-profile-api.zip
  env:
    COSMOS_ENDPOINT: $(SECRET_COSMOS-ENDPOINT)
    COSMOS_KEY: $(SECRET_COSMOS-KEY)
    AZURE_SUBSCRIPTION_ID: $(SECRET_AZURE-SUBSCRIPTION-ID)
    AZURE_CLIENT_ID: $(SECRET_AZURE-CLIENT-ID)
    AZURE_CLIENT_SECRET: $(SECRET_AZURE-CLIENT-SECRET)
    AZURE_TENANT_ID: $(SECRET_AZURE-TENANT-ID)
