service: pdlbrd-github-api

provider:
  resourceGroup: wabrez-westus-dev-paddleboard
  prefix: ${opt:prefix, 'sls'}
  name: azure
  region: West US
  runtime: nodejs10.x
  environment:
    STORAGE_CONNECTION: ${env:STORAGE_CONNECTION}
    COSMOS_ENDPOINT: ${env:COSMOS_ENDPOINT}
    COSMOS_KEY: ${env:COSMOS_KEY}
    QUEUE_ACCOUNT_NAME: ${env:QUEUE_ACCOUNT_NAME}
    QUEUE_ACCOUNT_KEY: ${env:QUEUE_ACCOUNT_KEY}
    GITHUB_APP_ID: ${env:GITHUB_APP_ID}
    GITHUB_CLIENT_ID: ${env:GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:GITHUB_CLIENT_SECRET}
    GITHUB_REDIRECT_URI: ${env:GITHUB_REDIRECT_URI}
    GITHUB_SIGNING_KEY: ${env:GITHUB_SIGNING_KEY}
  apim:
    name: wabrez-wus-dev-pdlbrd-apim
    apis:
      - name: github-api
        subscriptionRequired: false
        displayName: GitHub API
        description: GitHub REST API for connection to Github Provider
        protocols:
          - https
        path: github
        authorization: none
    backends:
      - name: github-backend
        url: api/github
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

plugins:
  - serverless-azure-functions
  - serverless-webpack

functions:
  # Github
  authorize:
    handler: src/handlers/github.authorize
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: github/authorize
          authLevel: function
    apim:
      api: github-api
      backend: github-backend
      operations:
        - method: GET
          urlTemplate: /authorize

  hook:
    handler: src/handlers/github.hook
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: github/hook
          authLevel: function
    apim:
      api: github-api
      backend: github-backend
      operations:
        - method: POST
          urlTemplate: /hook

  install:
    handler: src/handlers/github.install
    events:
      - queue: github-installations
        x-azure-settings:
          name: message # Specifies which name it's available on `context`
          connection: STORAGE_CONNECTION # App Setting/environment variable which contains Storage Account Connection String

