# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - packages/api-codereview

variables:
  - group: BackendResources

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'ci'
    workingDir: 'packages/api-codereview'

- task: Npm@1
  displayName: 'Linting & Testing'
  inputs:
    command: 'custom'
    workingDir: 'packages/api-codereview'
    customCommand: 'run test'
  env:
    COSMOS_ENDPOINT: $(COSMOS-ENDPOINT)
    COSMOS_KEY: $(COSMOS-KEY)

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: 'packages/api-codereview'
    customCommand: 'run build'
  env:
    COSMOS_ENDPOINT: $(COSMOS-ENDPOINT)
    COSMOS_KEY: $(COSMOS-KEY)
