service: pdlbrd-category-api

provider:
  resourceGroup: wabrez-westus-dev-paddleboard
  prefix: ${opt:prefix, 'sls'}
  name: azure
  region: West US
  runtime: nodejs10.x
  environment:
    COSMOS_ENDPOINT: ${env:COSMOS_ENDPOINT}
    COSMOS_KEY: ${env:COSMOS_KEY}
  apim:
    name: wabrez-wus-dev-pdlbrd-apim
    apis:
      - name: user-profile-api
        subscriptionRequired: false
        displayName: User Profile API
        description: User Profile REST API
        protocols:
          - https
        path: users
        authorization: none
      - name: current-user-api
        subscriptionRequired: false
        displayName: CurrentUser API
        description: CurrentUser REST API
        protocols:
          - https
        path: user
        authorization: none
    backends:
      - name: category-user-profile-backend
        url: api/users
      - name: category-current-user-backend
        url: api/user
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"

plugins:
  - serverless-azure-functions
  - serverless-webpack

functions:
  # Categories
  getCategoryListByUser:
    handler: src/handlers/category.getCategoryListByUser
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users/{userId}/categories
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: GET
          urlTemplate: /{userId}/categories
          templateParameters:
            - name: userId
              type: string

  getCategoryListByCurrentUser:
    handler: src/handlers/category.getCategoryListByUser
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: user/categories
          authLevel: function
    apim:
      api: current-user-api
      backend: category-current-user-backend
      operations:
        - method: GET
          urlTemplate: /categories

  getCategory:
    handler: src/handlers/category.getCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users/{userId}/categories/{categoryId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: GET
          urlTemplate: /{userId}/categories/{categoryId}
          templateParameters:
            - name: userId
              type: string
            - name: categoryId
              type: string

  getCategoryByCurrentUser:
    handler: src/handlers/category.getCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: user/categories/{categoryId}
          authLevel: function
    apim:
      api: current-user-api
      backend: category-current-user-backend
      operations:
        - method: GET
          urlTemplate: /categories/{categoryId}
          templateParameters:
            - name: categoryId
              type: string

  postCategory:
    handler: src/handlers/category.postCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: users/{userId}/categories
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: POST
          urlTemplate: /{userId}/categories
          templateParameters:
            - name: userId
              type: string

  putCategory:
    handler: src/handlers/category.putCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT
          route: users/{userId}/categories/{categoryId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: PUT
          urlTemplate: /{userId}/categories/{categoryId}
          templateParameters:
            - name: userId
              type: string
            - name: categoryId
              type: string

  patchCategory:
    handler: src/handlers/category.patchCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - PATCH
          route: users/{userId}/categories/{categoryId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: PATCH
          urlTemplate: /{userId}/categories/{categoryId}
          templateParameters:
            - name: userId
              type: string
            - name: categoryId
              type: string

  deleteCategory:
    handler: src/handlers/category.deleteCategory
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: users/{userId}/categories/{categoryId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: category-user-profile-backend
      operations:
        - method: DELETE
          urlTemplate: /{userId}/categories/{categoryId}
          templateParameters:
            - name: userId
              type: string
            - name: categoryId
              type: string
