service: pdlbrd-user-profile-api

provider:
  resourceGroup: wabrez-westus-dev-paddleboard
  prefix: ${opt:prefix, 'sls'}
  name: azure
  region: West US
  runtime: nodejs10.x
  environment:
    COSMOS_ENDPOINT: ${env:COSMOS_ENDPOINT}
    COSMOS_KEY: ${env:COSMOS_KEY}
  apim:
    name: wabrez-wus-dev-pdlbrd-apim
    apis:
      - name: user-profile-api
        subscriptionRequired: false
        displayName: UserProfile API
        description: UserProfile CRUD REST API
        protocols:
          - https
        path: users
        authorization: none
      - name: current-user-api
        subscriptionRequired: false
        displayName: CurrentUser API
        description: CurrentUser REST API
        protocols:
          - https
        path: user
        authorization: none
    backends:
      - name: user-profile-backend
        url: api/users
      - name: current-user-backend
        url: api/user
    cors:
      allowCredentials: false
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
      allowedHeaders:
        - "*"
      exposeHeaders:
        - "*"
    jwtValidate:
      headerName: authorization
      scheme: bearer
      failedStatusCode: 401
      failedErrorMessage: "Authorization token is missing or invalid"
      openId:
        metadataUrl: "https://paddleboard.b2clogin.com/paddleboard.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_signup_signin"
      audiences:
        - "a13be30d-bdd7-4b45-889f-adbdc16f01f6"
      issuers:
        - "https://paddleboard.b2clogin.com/82253bfc-02a2-46a0-8fae-acfaaf310db9/v2.0/"

plugins:
  - serverless-azure-functions
  - serverless-webpack

functions:
  # User Profiles
  getUserProfileList:
    handler: src/handlers/userProfile.getUserProfileList
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: GET
          urlTemplate: /

  getUserProfile:
    handler: src/handlers/userProfile.getUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: users/{userId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: GET
          urlTemplate: /{userId}
          templateParameters:
            - name: userId
              type: string

  getCurrentUserProfile:
    handler: src/handlers/userProfile.getCurrentUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          route: user
          authLevel: function
    apim:
      api: current-user-api
      backend: current-user-backend
      operations:
        - method: GET
          urlTemplate: /

  postUserProfile:
    handler: src/handlers/userProfile.postUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: users
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: POST
          urlTemplate: /

  postCurrentUserProfile:
    handler: src/handlers/userProfile.postCurrentUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - POST
          route: user
          authLevel: function
    apim:
      api: current-user-api
      backend: current-user-backend
      operations:
        - method: POST
          urlTemplate: /

  putUserProfile:
    handler: src/handlers/userProfile.putUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - PUT
          route: users/{userId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: PUT
          urlTemplate: /{userId}
          templateParameters:
            - name: userId
              type: string

  patchUserProfile:
    handler: src/handlers/userProfile.patchUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - PATCH
          route: users/{userId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: PATCH
          urlTemplate: /{userId}
          templateParameters:
            - name: userId
              type: string

  deleteUserProfile:
    handler: src/handlers/userProfile.deleteUserProfile
    events:
      - http: true
        x-azure-settings:
          methods:
            - DELETE
          route: users/{userId}
          authLevel: function
    apim:
      api: user-profile-api
      backend: user-profile-backend
      operations:
        - method: DELETE
          urlTemplate: /{userId}
          templateParameters:
            - name: userId
              type: string
