# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - packages/core

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'ci'
    workingDir: 'packages/core'

- task: Npm@1
  displayName: 'Linting & Testing'
  inputs:
    command: 'custom'
    workingDir: 'packages/core'
    customCommand: 'run test'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: 'packages/core'
    customCommand: 'run build'

- task: Npm@1
  displayName: 'Package NPM Package'
  inputs:
    command: 'pack'
    workingDir: 'packages/core'

- task: CopyFiles@2
  displayName: 'Prepare build artifact'
  inputs:
    SourceFolder: 'packages/core'
    Contents: 'paddleboard-core-1.0.0.tgz'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'core'
    publishLocation: 'Container'
