# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none

variables:
  - group: BackendResources
  - group: GithubCredentials

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: DownloadPipelineArtifact@2
  displayName: 'Download Build Artifact'
  inputs:
    targetPath: 'artifact'
    buildType: 'specific'
    specificBuildWithTriggering: true
    artifactName: 'core'
    project: 'paddleboard'
    pipelineId: 10
    buildVersionToDownload: latestFromBranch
    branchName: refs/heads/master

- task: Bash@3
  displayName: 'Publish NPM Package'
  inputs:
    targetType: filePath
    filePath: ./packages/core/scripts/publish.sh
    arguments: '@paddleboard/core'
    workingDirectory: artifact
  env:
    NPM_TOKEN: $(NPM-TOKEN)

- task: Npm@1
  displayName: 'Publish NPM Package'
  inputs:
    command: 'publish'
    publishEndpoint: 'NPM'
    workingDir: 'packages/core'
    customCommand: '$(System.ArtifactsDirectory)/core/paddleboard-core-1.0.0.tgz --access public'
